# Site settings
title: Cairo Graphics
baseurl: "/cairographics.org/" # the subpath of your site, e.g. /blog/
                                 # usually empty. necessary for building absolute URIs
                                 # for metadata header
url: "https://jimmac.github.io"   # the base hostname & protocol for your site
sourceurl: "https://github.com/jimmac/cairographics.org" # "edit this website" link in the footer
description: "Draw 2D using this graphics library."
issuesurl: "https://github.com/jimmac/cairographics.org/issues" # issue tracker for website
permalink: /:title/
primary-color: "#b39400" #used in ios theme. further color customization in style.css  

# Build settings
markdown: kramdown

collections:
  news:
    output: true
    permalink: "/cairographics.org/:collection/:title/"
    layout: news
